/**
 * Compile src/text/*.md into src/ts/primers.generated.ts.
 *
 * The per-side summaries are prose, and prose is easier to write and review as
 * Markdown than as a string literal wrapped in `_()`. But `*.md` is excluded
 * from the deploy, so the client can never read these files at runtime — they
 * have to be compiled in.
 *
 * Why a generated `.ts` full of `_('…')` calls rather than a rollup text
 * import: BGA finds translatable text by scanning the *deployed* files, which
 * for the client means `modules/js/Game.js`. A literal inside `_()` survives
 * into that bundle and stays translatable; `_(someImportedVariable)` extracts
 * nothing and would make these two paragraphs English for good.
 *
 * The generated file is committed for the same reason: it is the thing the
 * translation system reads, so it should be visible in review rather than
 * appearing only on whoever's machine ran the build.
 *
 * Markdown support is deliberately the subset these files use — blank-line
 * paragraphs, `**bold**`, `*italic*` — because a dependency for that would be
 * more code than the converter. `${placeholders}` are passed through untouched
 * for the caller to `.replace()`.
 *
 * Run by `npm run build`; `tools/deploy.sh` runs that before every sync.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const textDir = join(root, 'src', 'text');
const outFile = join(root, 'src', 'ts', 'primers.generated.ts');

/** `primer-rebels` -> `primerRebels`. */
const camel = name => name.replace(/[-_](.)/g, (_, c) => c.toUpperCase());

/** The Markdown subset these files use, as one HTML string per file. */
function toHtml(markdown) {
    const paragraphs = markdown
        .trim()
        .split(/\n\s*\n/)
        .map(block => block
            .replace(/\s*\n\s*/g, ' ')
            .trim()
            .replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')
            .replace(/(^|[^*])\*([^*]+?)\*/g, '$1<i>$2</i>'));

    return paragraphs.map(text => `<p>${text}</p>`).join('');
}

/** Single quotes and backslashes are the only things that can break `_('…')`. */
const quote = text => text.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const files = readdirSync(textDir).filter(name => name.endsWith('.md')).sort();

const body = files.map(name => {
    const key = camel(name.replace(/\.md$/, ''));
    const html = toHtml(readFileSync(join(textDir, name), 'utf8'));
    return `/** From \`src/text/${name}\`. Edit that file, not this one. */\n`
        + `export const ${key} = (): string => _('${quote(html)}');\n`;
}).join('\n');

writeFileSync(outFile, `/**
 * GENERATED by tools/build-text.mjs from src/text/*.md — do not edit.
 *
 * Each export is a function rather than a constant so that \`_()\` is called when
 * the text is needed rather than when this module is imported, which is before
 * BGA has installed the translator.
 */

${body}`);

console.log(`primers.generated.ts <- ${files.join(', ')}`);
