/**
 * GENERATED by tools/build-text.mjs from src/text/*.md — do not edit.
 *
 * Each export is a function rather than a constant so that `_()` is called when
 * the text is needed rather than when this module is imported, which is before
 * BGA has installed the translator.
 */

/** From `src/text/primer-empire.md`. Edit that file, not this one. */
export const primerEmpire = (): string => _('<p>You build ${troop} troops in ${city} cities, march them along roads, and keep them supplied by networks of occupied ${town} locations. When you think a ${troop} garrison outweighs the rebels\' ${presence} presence in a ${town} location, <b>resolve</b> it and find out: you score the ${presence} presence you capture, if you win.</p><p><b>You win ties.</b> A ${troop} garrison only has to match the ${presence} presence against it.</p>');

/** From `src/text/primer-rebels.md`. Edit that file, not this one. */
export const primerRebels = (): string => _('<p>You place <b>${hand} hidden ${agent} agents</b> on ${town} locations each turn — some are decoys, some carry real ${presence} presence, and you must place your whole hand. When you think a ${town} location\'s ${agent} cards overpower its ${troop} garrison, <b>resolve</b> it and find out: you score the ${presence} presence you drive out, if you win.</p><p><b>The Empire wins ties.</b> You have to <i>beat</i> a ${troop} garrison, not match it.</p>');
