/**
 * GENERATED by tools/build-text.mjs from src/text/*.md — do not edit.
 *
 * Each export is a function rather than a constant so that `_()` is called when
 * the text is needed rather than when this module is imported, which is before
 * BGA has installed the translator.
 */

/** From `src/text/primer-empire.md`. Edit that file, not this one. */
export const primerEmpire = (): string => _('<p>You build troops in cities, march them along roads, and keep them supplied by networks of occupied locations. When you think a garrison outweighs the rebels\' presence in a location, <b>resolve</b> it and find out: you score the presence you capture, if you win.</p><p><b>You win ties.</b> A garrison only has to match the presence against it.</p>');

/** From `src/text/primer-rebels.md`. Edit that file, not this one. */
export const primerRebels = (): string => _('<p>You place <b>${hand} hidden agents</b> on locations each turn — some are decoys, some carry real presence, and you must place your whole hand. When you think a location\'s cards overpower its garrison, <b>resolve</b> it and find out: you score the presence you drive out, if you win.</p><p><b>The Empire wins ties.</b> You have to <i>beat</i> a garrison, not match it.</p>');
